---
title: "Getting Started with Bayesian Inference in Julia"
format: html
jupyter: julia-1.11
---



```{julia}
cd(@__DIR__)
using Pkg
Pkg.activate(".")
Pkg.instantiate()

```

There is a package called `Turing.jl` that is a powerful tool for Bayesian inference in Julia. It allows you to define probabilistic models and perform inference using various algorithms. Compared to the R/Stan ecosystem, Julia + Turing has both upsides and downside. The main upside is that it allows to use both discrete and continuous distributions. Since the treatment of phylogenetic uncertainty requires marginalization over discrete entitites, this is a big plus. Another upside is that everything is written in one language, Julia, so you avoid the headache to come to grips with Stan. One of the downsides is that there are no off-the-shelf techniques for model comparison, so we will have to either implement them ourselves or to use the RCall interface to R.

We start with loading the necessary packages.

```{julia}
using Turing
using StatsPlots
using Distributions
using DataFrames
using CSV
using LinearAlgebra
using Pigeons
using Glob
using Phylo
using Pipe
using StatsFuns
using ProgressMeter
using Random
using LogDensityProblems
using DynamicPPL
using Kronecker
```


Now we load the data.

**Edge tree distribution**

```{julia}
# Create data directory if it doesn't exist
isdir("../data") || mkpath("../data")

# Paths
tgz_url = "https://github.com/rbouckaert/global-language-tree-pipeline/releases/download/v1.0.0/all_trees.tgz"
tgz_file = "../data/all_trees.tgz"
tar_file = "../data/all_trees.tar"
tree_dir = "../data/all_trees/"

# Download and extract
if !isdir(tree_dir)
    Downloads.download(tgz_url, tgz_file)

    # Decompress .tgz to .tar
    open(tgz_file) do f_in
        open(tar_file, "w") do f_out
            write(f_out, transcode(GzipDecompressor, read(f_in)))
        end
    end

    # Extract .tar archive
    Tar.extract(tar_file, tree_dir)
    # Move all files from ../data/all_trees/all_trees to ../data/all_trees
    inner_dir = joinpath(tree_dir, "all_trees")
    if isdir(inner_dir)
        for f in readdir(inner_dir; join=true)
            mv(f, joinpath(tree_dir, basename(f)); force=true)
        end
        rm(inner_dir; force=true, recursive=true)
    end
    # Clean up
    rm(tgz_file)
    rm(tar_file)
end


# Load all Newick trees
tree_files = glob("*.tree", tree_dir)

trees = [parsenewick(read(f, String)) for f in tree_files]

# Optionally strip suffixes
for tree in trees
    for tip in getleaves(tree)
        tip.name = split(tip.name, "_")[1]
    end
end

```


**Grambank data**


```{julia}
#| vscode: {languageId: julia}

full_taxa = intersect(getleafnames.(trees)...)


Random.seed!(1234)  # Set seed for reproducibility
d = @pipe CSV.File("../data/grambank_vals_pruned.csv") |>
          DataFrame |>
          unique(_, :Language_ID) |>
          filter(row -> row.Language_ID in full_taxa, _) |>
          _[randperm(nrow(_))[1:20], :] |>
          sort(_, :Language_ID)
taxa = d.Language_ID
```


Now we prune the trees to only include the languages in the data.

```{julia}
#| vscode: {languageId: julia}
pruned_trees = [deepcopy(t) for t in rand(trees, 50)]
for t in pruned_trees
    droptips!(t, setdiff(getleafnames(t), taxa))
end
```

```{julia}
taxa = getleafnames(pruned_trees[1])

filter!(row -> row.Language_ID in taxa, d)
```


Let us add a combined character `z` to the data, which is $2x+y-1$. 


To illustrate the advantage of the Julia + Turing approach, I implemented the likelihood function for the joint model according to Pagel & Meade (2006) in Julia. The function `get_ll` computes the log-likelihood of the data given a tree and a rate matrix $Q$. The function `decompose_tree` is used to extract the necessary information from the tree structure.


First we create the new character `z` in the data frame `d` that captures the possible combination states of the two characters `x` and `y`. The new character is defined as $z = 2x + y - 1$.


```{julia}
#| vscode: {languageId: julia}
#| output: false

d = @pipe d |> transform(_, [:x, :y] => ByRow((x, y) -> 2x + y + 1) => :z)

```

Then we add the likelihood function `get_ll` as a function of a tree `tree`, a rate matrix `Q`, tip labels `taxa`, and a vector `z` of states for the tip labels. The function `decompose_tree` is a helper function that extracts the necessary information from the tree structure.
```{julia}

function decompose_tree(
    tree::RootedTree
)::@NamedTuple{root::String, mothers::Vector{String}, daughters::Vector{String}, lengths::Vector{Float64}, nodes_dict::Dict{String,Int64}}
    root = getroot(tree).name
    mothers = String[]
    daughters = String[]
    lengths = Float64[]
    for nd in traversal(tree, postorder)
        if !isroot(tree, nd)
            mother = getparent(tree, nd)
            br = getinbound(tree, nd)
            bl = getlength(tree, br)
            push!(mothers, mother.name)
            push!(daughters, nd.name)
            push!(lengths, bl)
        end
    end

    nodes = sort!(unique(vcat(mothers, daughters)))
    nodes_dict = Dict{String,Int}(nodes .=> 1:length(nodes))
    (root=root, mothers=mothers, daughters=daughters, lengths=lengths, nodes_dict=nodes_dict)
end

```

```{julia}
function get_P(
    t::Float64,
    Q::AbstractMatrix{Float64},
)::Matrix{Float64}
    exp(Q * t)
end

function rates_to_matrix(rates::Vector{Float64}; nstates=4)
    Q = zeros(Float64, nstates, nstates)
    counter = 1
    for i in 1:nstates, j in 1:nstates
        if i != j
            Q[i, j] = min(rates[counter], 1e10)
            counter += 1
        end
    end
    for i in 1:nstates
        Q[i, i] = -sum(Q[i, :])
    end
    return Q
end


function get_ll(
    tree::RootedTree,
    Q::AbstractMatrix;
    taxa=d.Language_ID,
    z::Vector{Int}=d.z
)::Float64
    eq = get_P(1000.0, Q)[:, 1]
    root, mothers, daughters, lengths, nodes_dict = decompose_tree(tree)
    ll = zeros(Float64, length(nodes_dict), maximum(z))
    for (l, s) in zip(taxa, z)
        ll[nodes_dict[l], :] .= -Inf
        ll[nodes_dict[l], s] = 0.0
    end
    @views for i in eachindex(lengths)
        dgt = nodes_dict[daughters[i]]
        mth = nodes_dict[mothers[i]]
        P = get_P(lengths[i], Q)
        tmp = log.(P) .+ ll[dgt, :]'
        for j in 1:size(tmp, 1)
            ll[mth, j] += logsumexp(view(tmp, j, :))
        end
    end
    logsumexp(ll[nodes_dict[root], :] + log.(eq))
end
```



Now we create a Turing model using this likelihood function. The model will have a prior on the rate matrix $Q$ and will use the `get_ll` function to compute the log-likelihood of the data given the tree and the rate matrix.

```{julia}


@model function ctmc_dependent_model(pruned_trees, taxa, z)
    urates ~ filldist(Normal(0.0, 1.0), 12)
    rates = exp.(urates)  # lognormal prior
    Q = rates_to_matrix(rates)

    latent_index ~ Normal(0.0, 1.0)
    n = length(pruned_trees)
    tree_index = clamp(Int(ceil(cdf(Normal(0.0, 1.0), latent_index) * n)), 1, n)

    tree = pruned_trees[tree_index]

    ll = get_ll(tree, Q; taxa=taxa, z=z)
    if DynamicPPL.leafcontext(__context__) !== DynamicPPL.PriorContext()
        Turing.@addlogprob! ll
    end
    return vcat(rates, [tree_index])
end

```


This model defines a prior on the rates using an exponential distribution, constructs the rate matrix $Q$ from the rates, and computes the log-likelihood of the data given the tree and the rate matrix using the `get_ll` function. The model can then be used for Bayesian inference using Turing's sampling algorithms.

The main difference from the R/Stan approach is that we can simultaneously sample from the tree space and the rate space, which is not possible in Stan. In Stan, you would have to compute the likelihood for all trees in the tree sample in each sampling step, which is computationally expensive. In Julia + Turing, we can sample from the tree space and the rate space simultaneously, which is much more efficient.


```{julia}
model_ctmc_dependent = ctmc_dependent_model(pruned_trees, taxa, d.z)

```

We can now sample from the model using the Metropolis-Hastings algorithm with MCMCThreads. This will allow us to sample from the posterior distribution of the rates and the tree index.

```{julia}

pt_ctmc_dependent = pigeons(
    target=TuringLogPotential(model_ctmc_dependent),
    n_chains = 2,
    multithreaded=true,
    record=[traces; record_default()]
)
println(stepping_stone(pt_ctmc_dependent))
```


```{julia}

chains_ctmc_dependent = Chains(
    sample_array(pt_ctmc_dependent),
    sample_names(pt_ctmc_dependent)
)

display(chains_ctmc_dependent)
plot(chains_ctmc_dependent)



```



```{julia}

@model function ctmc_independent_model(pruned_trees, taxa, x, y)
    urates_x ~ filldist(Normal(0.0, 1.0), 2)
    rates_x = exp.(urates_x)  # lognormal prior
    Q_x = rates_to_matrix(rates_x, nstates=2)

    urates_y ~ filldist(Normal(0.0, 1.0), 2)
    rates_y = exp.(urates_y)  # lognormal prior
    Q_y = rates_to_matrix(rates_y, nstates=2)

    latent_index ~ Normal(0.0, 1.0)
    n = length(pruned_trees)
    tree_index = clamp(Int(ceil(cdf(Normal(0.0, 1.0), latent_index) * n)), 1, n)

    tree = pruned_trees[tree_index]

    ll_x = get_ll(tree, Q_x; taxa=taxa, z=x .+ 1)
    ll_y = get_ll(tree, Q_y; taxa=taxa, z=y .+ 1)
    if DynamicPPL.leafcontext(__context__) !== DynamicPPL.PriorContext()
        Turing.@addlogprob! ll_x
        Turing.@addlogprob! ll_y
    end
    return vcat(rates_x, rates_y, [tree_index])
end
```

```{julia}
model_ctmc_independent = ctmc_independent_model(pruned_trees, taxa, d.x, d.y)

pt_ctmc_independent = pigeons(
    target=TuringLogPotential(model_ctmc_independent),
    n_chains = 2,
    multithreaded=true,
    record=[traces; record_default()]
)

println(stepping_stone(pt_ctmc_independent))

```


```{julia}

chains_ctmc_independent = Chains(
    sample_array(pt_ctmc_independent),
    sample_names(pt_ctmc_independent)
)

display(chains_ctmc_independent)
plot(chains_ctmc_independent)



```


```{julia}

@model function brownian_regression_recursive(pruned_trees, taxa, x)
    alpha ~ LocationScale(0, 2.5, TDist(3))
    beta ~ Normal(0, 2)
    latent_index ~ Normal(0.0, 1.0)
    n = length(pruned_trees)
    tree_index = clamp(Int(ceil(cdf(Normal(0.0, 1.0), latent_index) * n)), 1, n)
    tree = pruned_trees[tree_index]
    urate ~ Normal()
    rate := exp(urate)

    root, mothers, daughters, lengths, nodes_dict = decompose_tree(tree)
    z_std ~ MvNormal(zeros(length(mothers)), ones(length(mothers)))
    z = zeros(Float64, length(nodes_dict))
    z[nodes_dict[root]] = 0.0
    for i in length(mothers):-1:1
        dgt = nodes_dict[daughters[i]]
        mth = nodes_dict[mothers[i]]
        z[dgt] = z[mth] + sqrt(rate * lengths[i]) * z_std[i]
    end
    z_tips = [z[nodes_dict[l]] for l in taxa]
    eta = alpha .+ beta * (x .- mean(x)) + z_tips

    y ~ product_distribution(BernoulliLogit.(eta))
end

```


```{julia}

function brownian_regression_recursive_target(pruned_trees=pruned_trees, taxa=taxa, x=d.x, y=d.y)
    return Pigeons.TuringLogPotential(brownian_regression_recursive(pruned_trees, taxa, d.x) | (y=d.y,))
end

BrownianRegressionRecursiveType = typeof(brownian_regression_recursive_target())

function Pigeons.initialization(target::BrownianRegressionRecursiveType, rng::AbstractRNG, ::Int64)
    # First run the model to populate all variables
    result = DynamicPPL.VarInfo(rng, target.model, DynamicPPL.SampleFromPrior(), DynamicPPL.PriorContext())

    # Link the variables to their transformed space
    result = DynamicPPL.link(result, target.model)

    return result
end

inputs_brownian_regression_recursive = Inputs(
    target=brownian_regression_recursive_target(),
    n_chains = 4,
    multithreaded=true,
    record=[traces; record_default()]
)


pt_brownian_regression_recursive = pigeons(inputs_brownian_regression_recursive)


println(stepping_stone(pt_brownian_regression_recursive))

```

```{julia}

chains_brownian_regression_recursive = Chains(
    sample_array(pt_brownian_regression_recursive),
    sample_names(pt_brownian_regression_recursive)
)

display(chains_brownian_regression_recursive[:, ["alpha", "beta", "urate", "latent_index"], :])

plot(chains_brownian_regression_recursive[:, ["alpha", "beta", "urate", "latent_index"], :])


```


```{julia}

@model function brownian_correlation_recursive(pruned_trees, taxa)
    rho ~ Uniform(-0.999, 0.999)
    Sigma := [1.0 rho; rho 1.0]
    n = length(pruned_trees)
    latent_index ~ Uniform(0, n)
    tree_index = clamp(Int(ceil(latent_index)), 1, n)
    tree = pruned_trees[tree_index]
    rates ~ filldist(LogNormal(0.0, 1.0), 2)

    root, mothers, daughters, lengths, nodes_dict = decompose_tree(tree)
    z_std ~ filldist(MvNormal(zeros(2), Sigma), length(mothers))
    z = zeros(Float64, (2, length(nodes_dict)))
    mu ~ filldist(Normal(0, 10.0), 2)
    z[:, nodes_dict[root]] .= mu
    for i in length(mothers):-1:1
        dgt = nodes_dict[daughters[i]]
        mth = nodes_dict[mothers[i]]
        for k in 1:2
            z[k, dgt] = z[k, mth] + sqrt(rates[k] * lengths[i]) * z_std[k, i]
        end
    end
    z_tips = hcat([z[:, nodes_dict[l]] for l in taxa]...)
    x ~ product_distribution(BernoulliLogit.(z_tips[1,:]))
    y ~ product_distribution(BernoulliLogit.(z_tips[2,:]))
end

```


```{julia}

function brownian_correlation_recursive_target(pruned_trees=pruned_trees, taxa=taxa, x = d.x, y=d.y)
    return Pigeons.TuringLogPotential(brownian_correlation_recursive(pruned_trees, taxa) | (x = d.x, y=d.y,))
end

BrownianCorrelationRecursiveType = typeof(brownian_correlation_recursive_target())

function Pigeons.initialization(target::BrownianCorrelationRecursiveType, rng::AbstractRNG, ::Int64)
    # First run the model to populate all variables
    result = DynamicPPL.VarInfo(rng, target.model, DynamicPPL.SampleFromPrior(), DynamicPPL.PriorContext())

    # Link the variables to their transformed space
    result = DynamicPPL.link(result, target.model)

    return result
end

inputs_brownian_correlation_recursive = Inputs(
    target=brownian_correlation_recursive_target(),
    n_chains = 5,
    multithreaded=true,
    record=[traces; record_default()]
)


pt_brownian_correlation_recursive = pigeons(inputs_brownian_correlation_recursive)


println(stepping_stone(pt_brownian_correlation_recursive))

```

```{julia}

chains_brownian_correlation_recursive = Chains(
    sample_array(pt_brownian_correlation_recursive),
    sample_names(pt_brownian_correlation_recursive)
)

display(chains_brownian_correlation_recursive[:, ["rho", "rates[1]", "rates[2]", "latent_index"], :])

plot(chains_brownian_correlation_recursive[:, ["rho", "rates[1]", "rates[2]", "latent_index"], :])


```



```{julia}

function get_vcv(tree; taxa=taxa)
    root = getroot(tree)
    tips = getleaves(tree)
    tip_names = getleafnames(tree)
    vcv = zeros(length(tips), length(tips))

    # Compute VCV matrix (upper triangle only)
    for i in 1:length(tips)
        for j in i:length(tips)
            if i == j
                # Diagonal: total distance from root to tip (variance)
                vcv[i, j] = distance(tree, root, tips[i])
            else
                # Off-diagonal: shared evolutionary time (distance from root to MRCA)
                vcv[j, i] = vcv[i, j] = distance(tree, root, mrca(tree, [tips[i], tips[j]]))
            end
        end
    end
    return vcv[indexin(tip_names, taxa), indexin(tip_names, taxa)]
end

```

```{julia}

vcv_matrices = [get_vcv(t, taxa=taxa) for t in pruned_trees]

cholesky_matrices = [cholesky(vcv).L for vcv in vcv_matrices] 

```



```{julia}
@model function brownian_correlation_kronecker(cholesky_matrices)
    rho ~ Uniform(-0.999, 0.999)
    Sigma_l = [1.0 0; rho sqrt(1.0-rho^2)]
    n = length(pruned_trees)
    latent_index ~ Uniform(0, n)
    tree_index = clamp(Int(ceil(latent_index)), 1, n)
    m = cholesky_matrices[tree_index]
    rates ~ filldist(LogNormal(0.0, 1.0), 2)

    product_matrix = Matrix(m ⊗ Sigma_l)

    mu ~ filldist(Normal(0, 10.0), 2)
    z_std ~ filldist(Normal(), size(product_matrix, 1))
    z = reshape(product_matrix * z_std, 2, :) .+ mu
    x ~ product_distribution(BernoulliLogit.(rates[1]^2 .* z[1,:]))
    y ~ product_distribution(BernoulliLogit.(rates[2]^2 .* z[2,:]))
    return (tree_index = tree_index,)
end



```



```{julia}

function brownian_correlation_kronecker_target(vcv_matrices=vcv_matrices, x=d.x, y=d.y)
    return Pigeons.TuringLogPotential(brownian_correlation_kronecker(vcv_matrices) | (x = d.x, y=d.y,))
end

BrownianCorrelationKroneckerType = typeof(brownian_correlation_kronecker_target())

function Pigeons.initialization(target::BrownianCorrelationRecursiveType, rng::AbstractRNG, ::Int64)
    # First run the model to populate all variables
    result = DynamicPPL.VarInfo(rng, target.model, DynamicPPL.SampleFromPrior(), DynamicPPL.PriorContext())

    # Link the variables to their transformed space
    result = DynamicPPL.link(result, target.model)

    return result
end

inputs_brownian_correlation_kronecker = Inputs(
    target=brownian_correlation_kronecker_target(),
    n_chains = 5,
    multithreaded=true,
    record=[traces; record_default()]
)


pt_brownian_correlation_kronecker = pigeons(inputs_brownian_correlation_kronecker)


println(stepping_stone(pt_brownian_correlation_kronecker))

```


```{julia}

chains_brownian_correlation_kronecker = Chains(
    sample_array(pt_brownian_correlation_kronecker),
    sample_names(pt_brownian_correlation_kronecker)
)

display(chains_brownian_correlation_kronecker[:, ["rho", "rates[1]", "rates[2]", "latent_index"], :])

plot(chains_brownian_correlation_kronecker[:, ["rho", "rates[1]", "rates[2]", "latent_index"], :])


```

############



```{julia}

@model function OU_correlation_recursive(pruned_trees, taxa)
    rho ~ Uniform(-0.999, 0.999)
    sigma ~ LogNormal(0.0, 1.0)
    mu ~ filldist(Normal(0, 2.0), 2)
    lambda ~ filldist(LogNormal(0.0, 1.0), 2)

    Sigma = [1.0 rho; rho 1.0]
    L_std = cholesky(Sigma).L
    n = length(pruned_trees)
    latent_index ~ Uniform(0, n)
    tree_index = clamp(Int(ceil(latent_index)), 1, n)
    tree = pruned_trees[tree_index]

    root, mothers, daughters, lengths, nodes_dict = decompose_tree(tree)
    z_std ~ filldist(MvNormal(zeros(2), ones(2)), length(nodes_dict))
    z = zeros(Float64, (2, length(nodes_dict)))
    z[:, nodes_dict[root]] .= mu .+ (sigma ./ sqrt.(2 .* lambda)) .* (L_std * z_std[:, nodes_dict[root]])
    for i in length(mothers):-1:1
        dgt = nodes_dict[daughters[i]]
        mth = nodes_dict[mothers[i]]
        decay = exp.(-lambda * lengths[i])
        s = sigma .* sqrt.(-expm1.(-2 * lambda * lengths[i]) ./ (2 * lambda))
        mn = mu .+ (z[:,mth] - mu) .* decay
        eps = L_std * z_std[:,dgt]
        z[:,dgt] = (mn .+ s .* eps)
    end
    z_tips = hcat([z[:, nodes_dict[l]] for l in taxa]...)
    x ~ product_distribution(BernoulliLogit.(z_tips[1,:]))
    y ~ product_distribution(BernoulliLogit.(z_tips[2,:]))
end

```


```{julia}

function OU_correlation_recursive_target(pruned_trees=pruned_trees, taxa=taxa, x = d.x, y=d.y)
    return Pigeons.TuringLogPotential(OU_correlation_recursive(pruned_trees, taxa) | (x = d.x, y=d.y,))
end

OUCorrelationRecursiveType = typeof(OU_correlation_recursive_target())

function Pigeons.initialization(target::OUCorrelationRecursiveType, rng::AbstractRNG, ::Int64)
    # First run the model to populate all variables
    result = DynamicPPL.VarInfo(rng, target.model, DynamicPPL.SampleFromPrior(), DynamicPPL.PriorContext())

    # Link the variables to their transformed space
    result = DynamicPPL.link(result, target.model)

    return result
end

inputs_OU_correlation_recursive = Inputs(
    target=OU_correlation_recursive_target(),
    n_chains = 5,
    multithreaded=true,
    record=[traces; record_default()]
)


pt_OU_correlation_recursive = pigeons(inputs_OU_correlation_recursive)


println(stepping_stone(pt_OU_correlation_recursive))

```

```{julia}

chains_OU_correlation_recursive = Chains(
    sample_array(pt_OU_correlation_recursive),
    sample_names(pt_OU_correlation_recursive)
)

display_names = [nm for nm in sample_names(pt_OU_correlation_recursive) if !occursin("z", String(nm))]


display(chains_OU_correlation_recursive[:, display_names, :])

plot(chains_OU_correlation_recursive[:, display_names, :])


```




```{julia}
```
