---
title: "Phylogenetic OU Regression with Julia"
format: html
jupyter: julia-1.11
---

# Including phylogenetic uncertainty - Julia version

Often, we do not have a single phylogeny but a set of phylogenies, e.g., from a Bayesian phylogenetic inference. When using phylogenetic control, we want to marginalize over the phylogenetic uncertainty. Doing this in R + Stan is possible but cumbersome and computationally expensive. Therefore I will explore re-implementations of the R/Stan models in Julia + Turing.jl, and in Python + NumPyro.

Let's start with Julia.


## Preparing the environment

```{julia}
cd(@__DIR__)
using Pkg
Pkg.activate(".")
Pkg.instantiate()

```

## Loading the required packages

```{julia}
using CodecZlib: GzipDecompressor
using CSV
using DataFrames
using DataFramesMeta
using Distributions
using Downloads
using DynamicPPL
using FileIO
using Glob
using LinearAlgebra
using LogDensityProblems
using MCMCChains
using Optim
using Phylo
using Pipe
using Printf
using ProgressMeter
using RCall
using Statistics
using StatsBase
using StatsFuns
using StatsPlots
using Tar
using Main.Threads
using Turing
```

## Data

Now we will use the 902 posterior samples of the EDGE tree.
```{julia}
# Create data directory if it doesn't exist
isdir("../data") || mkpath("../data")

# Paths
tgz_url = "https://github.com/rbouckaert/global-language-tree-pipeline/releases/download/v1.0.0/all_trees.tgz"
tgz_file = "../data/all_trees.tgz"
tar_file = "../data/all_trees.tar"
tree_dir = "../data/all_trees/"

# Download and extract
if !isdir(tree_dir)
    Downloads.download(tgz_url, tgz_file)

    # Decompress .tgz to .tar
    open(tgz_file) do f_in
        open(tar_file, "w") do f_out
            write(f_out, transcode(GzipDecompressor, read(f_in)))
        end
    end

    # Extract .tar archive
    Tar.extract(tar_file, tree_dir)
    # Move all files from ../data/all_trees/all_trees to ../data/all_trees
    inner_dir = joinpath(tree_dir, "all_trees")
    if isdir(inner_dir)
        for f in readdir(inner_dir; join=true)
            mv(f, joinpath(tree_dir, basename(f)); force=true)
        end
        rm(inner_dir; force=true, recursive=true)
    end
    # Clean up
    rm(tgz_file)
    rm(tar_file)
end


# Load all Newick trees
tree_files = glob("*.tree", tree_dir)

trees = [parsenewick(read(f, String)) for f in tree_files]

# Optionally strip suffixes
for tree in trees
    for tip in getleaves(tree)
        tip.name = split(tip.name, "_")[1]
    end
end

```


## Grambank data

We use the same sample as in the previous notebook

```{julia}
#| vscode: {languageId: julia}

d = @pipe CSV.File("../data/grambank_vals_pruned.csv") |>
          DataFrame |>
          sort(_, :Language_ID)
taxa = d.Language_ID
```


Now we prune the trees to only include the languages in the data.

```{julia}
#| vscode: {languageId: julia}
pruned_trees = [deepcopy(t) for t in trees]
for t in pruned_trees
    droptips!(t, setdiff(getleafnames(t), taxa))
end
```


## Vanilla regression

We will use the same model as in the previous notebook, but now we will use Turing.jl to implement it.

The likelihood is implemented as a Turing model like this:

```{julia}
#| vscode: {languageId: julia}
@model function vanilla_regression(x, y)
    N = length(y)

    # Center x
    means_x = mean(x)
    Xc = x .- means_x

    # Priors
    alpha ~ LocationScale(0, 2.5, TDist(3))
    beta ~ Normal(0, 2)

    # Likelihood - vectorized for efficiency
    # Linear predictor
    η = alpha .+ beta .* Xc

    # Bernoulli logistic likelihood
    for i in 1:N
        y[i] ~ BernoulliLogit(η[i])
    end
end
```

The `generated quantities` block from the Stan model is implemented as a separate function:

```{julia}
#| vscode: {languageId: julia}
#| 
# Log-likelihood, posterior predictive, and prior predictive in a function:
function generated_quantities(chain, x, y)
    N = length(y)
    means_x = mean(x)
    Xc = x .- means_x

    nsamples = length(chain[:alpha])
    loglik = zeros(nsamples, N)
    y_rep = zeros(Int, nsamples, N)
    y_prior = zeros(Int, nsamples, N)

    for s in 1:nsamples
        α = chain[:alpha][s]
        β = chain[:beta][s]

        for n in 1:N
            # log-likelihood (using centered x for consistency)
            loglik[s, n] = logpdf(BernoulliLogit(α + β * Xc[n]), y[n])

            # posterior predictive
            y_rep[s, n] = rand(BernoulliLogit(α + β * Xc[n]))

            # prior predictive
            αp = rand(LocationScale(0, 2.5, TDist(3)))
            βp = rand(Normal(0, 2))
            y_prior[s, n] = rand(BernoulliLogit(αp + βp * Xc[n]))
        end
    end

    return (loglik=loglik, y_rep=y_rep, y_prior=y_prior)
end
```

Let's run the model:

```{julia}
#| vscode: {languageId: julia}

# Run the model
@time begin
    model_vanilla_regression = vanilla_regression(d.x, d.y)
    chain_vanilla_regression = sample(
        model_vanilla_regression,
        NUTS(),
        MCMCThreads(),
        1000,
        4,
        discard_initial=1000,
        progress=true,
    )

end
# Print summary of the chain
describe(chain_vanilla_regression)
```

The 95% credible intervals for the parameters are:

```{julia}
#| vscode: {languageId: julia}

hpd(chain_vanilla_regression)
```


```{julia}
#| vscode: {languageId: julia}
# plot the posterior distributions of alpha and beta

ridgelineplot(chain_vanilla_regression, [:beta], title="Posterior distributions of beta")

```

This looks reassuringly similar to the R/Stan model. Now let's plot the prior and posterior predictive distributions.

```{julia}

function predictive_checks_regression(y_rep, y_prior; d=d)
    obs_0 = mean(d.y[d.x.==0])
    obs_1 = mean(d.y[d.x.==1])
    # Define colors
    CBblue = RGB(0.0, 114 / 255, 178 / 255)
    CBvermillion = RGB(213 / 255, 94 / 255, 0.0)

    p0 = density(vec(mean(y_prior[:, d.x.==0]; dims=2)),
        fill=(0, 0.5, CBblue),
        label="Prior",
        title="P(y=1|x=0)"
    )
    density!(p0, vec(mean(y_rep[:, d.x.==0]; dims=2)),
        fill=(0, 0.5, CBvermillion),
        label="Posterior")
    vline!(p0, [obs_0], color=:black, label="", linewidth=2)


    p1 = density(vec(mean(y_prior[:, d.x.==1]; dims=2)),
        fill=(0, 0.5, CBblue),
        label=false,
        title="P(y=1|x=1)"
    )
    density!(p1, vec(mean(y_rep[:, d.x.==1]; dims=2)),
        fill=(0, 0.5, CBvermillion),
        label=false
    )
    vline!(p1, [obs_1], color=:black, label="", linewidth=2)


    link = :both
    plot(p0, p1, layout=(2, 1), link=:x, legend=:topleft)
end

```

```{julia}
#| vscode: {languageId: julia}
gq_vanilla_regression = generated_quantities(chain_vanilla_regression, d.x, d.y)

predictive_checks_regression(gq_vanilla_regression.y_rep, gq_vanilla_regression.y_prior)
```

Next we compute the marginal log-likelihood and the LOOIC.

```{julia}
#| vscode: {languageId: julia}


function create_logdensity_function(model)
    # Create a LogDensityProblems-compatible object
    logdensity_obj = DynamicPPL.LogDensityFunction(model)

    return function (params::Vector{Float64})
        # Use LogDensityProblems.logdensity instead of DynamicPPL.logdensity
        return LogDensityProblems.logdensity(logdensity_obj, params)
    end
end

```

```{julia}
#| vscode: {languageId: julia}
# Compute log-likelihood
logdensity_func_vanilla_regression = create_logdensity_function(model_vanilla_regression)


```

```{julia}

samples_vanilla_regression = [Vector(chain_vanilla_regression[:alpha][:]) Vector(chain_vanilla_regression[:beta][:])]

```

```{julia}
#| vscode: {languageId: julia}

function bridge_sampling(
    samples::Array{Float64,2},
    log_density::Function
)
    nr = size(samples, 1) ÷ 2
    samples_4_fit = permutedims(Array(samples[1:nr, :]))
    samples_4_iter = permutedims(Array(samples[(nr+1):end, :]))
    r0 = 0.5
    tol1 = 1e-10
    n_post = size(samples_4_iter, 2)
    m = vec(mapslices(mean, samples_4_fit, dims=2))::Vector{Float64}
    V = diagm(ones(size(samples, 2)))
    q11 = Vector{Float64}(undef, n_post) # unnormalized posterior
    @threads for i = 1:n_post
        q11[i] = log_density(Array(samples_4_iter[:, i]))
    end
    q12 = Vector{Float64}(undef, n_post) # g
    @threads for i = 1:n_post
        q12[i] = logpdf(MvNormal(m, V), samples_4_iter[:, i])
    end
    gen_samples = rand(MvNormal(m, V), n_post)
    q21 = Vector{Float64}(undef, n_post) # unnormalized posterior
    @threads for i = 1:n_post
        q21[i] = log_density(gen_samples[:, i])
    end
    q22 = Vector{Float64}(undef, n_post) # g
    @threads for i = 1:n_post
        q22[i] = logpdf(MvNormal(m, V), gen_samples[:, i])
    end
    l1 = q11 - q12 # samples_4_iter, unnormalized posterior / g
    l2 = q21 - q22# gen_samples, unnormalized posterior / g
    lstar = median(l1)
    n_1 = length(l1)
    n_2 = length(l2)
    neff = (1.0 * n_1)::Float64
    try
        neff = minimum(summarystats(sim).value[:, end, 1])
    catch e
    end
    s1 = neff ./ (neff .+ n_2)
    s2 = n_2 ./ (neff .+ n_2)
    logr = log(r0)
    log_r_vals = [logr]::Vector{Float64}
    logml = logr + lstar

    function upd(logr)
        lognumi = logsumexp([
            l2[i] - lstar - logaddexp(log(s1) + l2[i] - lstar, log(s2) + logr) for
            i = 1:size(l2, 1)
        ])
        logdeni = logsumexp([
            -logaddexp(log(s1) + l1[i] - lstar, log(s2) .+ logr) for
            i = 1:size(l1, 1)
        ])
        log(n_1) - log(n_2) + lognumi - logdeni
    end

    ft = optimize(y -> (upd(y) - y)^2, -10000., 0.)
    ft.minimizer + lstar

end
```

```{julia}
#| vscode: {languageId: julia}
# Compute marginal log-likelihood
logml_vanilla_regression = bridge_sampling(samples_vanilla_regression, logdensity_func_vanilla_regression)
println("Marginal log-likelihood: ", logml_vanilla_regression)
```


```{julia}
#| vscode: {languageId: julia}
# Compute LOOIC
loo_vanilla_regression = convert(
    Dict,
    R"
    library(loo)
    loo($(gq_vanilla_regression.loglik))
    ",
);
```

```{julia}
#| vscode: {languageId: julia}

# Alternative: Create a more structured view of LOO results
function format_loo_results(loo_dict)
    # Extract the main metrics
    estimates = DataFrame(
        metric=["LOOIC", "SE of LOOIC", "elpd_loo", "SE of elpd_loo"],
        value=[
            loo_dict["looic"],
            loo_dict["se_looic"],
            loo_dict["elpd_loo"],
            loo_dict["se_p_loo"]
        ]
    )
    return estimates
end

```

```{julia}
# Print LOO results
println("LOO Results:")
loo_results_vanilla_regression = format_loo_results(loo_vanilla_regression)
println(loo_results_vanilla_regression)
```

```{julia}
#| vscode: {languageId: julia}

@model function vanilla_correlation(x, y)
    N = length(y)

    # Priors
    μ1 ~ Normal(0, 2.0)
    μ2 ~ Normal(0, 2.0)
    ρ ~ Uniform(-1, 1)

    # Construct covariance matrix from correlation
    Σ = [1.0 ρ; ρ 1.0]
    μ = [μ1, μ2]
    
    # Sample latent variables directly from multivariate normal
    for n in 1:N
        z[n] ~ MvNormal(μ, Σ)
        
        # Likelihood
        x[n] ~ BernoulliLogit(z[n][1])
        y[n] ~ BernoulliLogit(z[n][2])
    end
end


```

```{julia}
#| vscode: {languageId: julia}

@time begin
    model_vanilla_correlation = vanilla_correlation(d.x, d.y)
    chain_vanilla_correlation = sample(
        model_vanilla_correlation,
        NUTS(),
        MCMCThreads(),
        1000,
        4,
        discard_initial=1000,
        progress=true,
    )

end
# Print summary of the chain
describe(
    chain_vanilla_correlation[:, [:μ1, :μ2, :ρ], :]
)

```

```{julia}
#| vscode: {languageId: julia}

hpd(chain_vanilla_correlation[:, [:μ1, :μ2, :ρ], :])
```

```{julia}
#| vscode: {languageId: julia}
# plot the posterior distributions of alpha and beta

ridgelineplot(chain_vanilla_correlation, [:ρ], title="Posterior distributions of ρ")

```

# Prior and posterior predictive sampling for vanilla_correlation

```{julia}
function generated_quantities_correlation(chain, x, y)
    N = length(y)
    nsamples = length(chain[:μ1])
    loglik = zeros(nsamples, N)
    y_rep = zeros(Int, nsamples, N)
    x_rep = zeros(Int, nsamples, N)
    y_prior = zeros(Int, nsamples, N)
    x_prior = zeros(Int, nsamples, N)

    for s in 1:nsamples
        μ1 = chain[:μ1][s]
        μ2 = chain[:μ2][s]
        ρ = chain[:ρ][s]
        
        # Construct covariance matrix
        μ = [μ1, μ2]
        Σ = [1.0 ρ; ρ 1.0]
        
        # Posterior predictive
        for n in 1:N
            z = rand(MvNormal(μ, Σ))
            x_rep[s, n] = rand(BernoulliLogit(z[1]))
            y_rep[s, n] = rand(BernoulliLogit(z[2]))
            loglik[s, n] = logpdf(BernoulliLogit(z[2]), y[n])
        end
        
        # Prior predictive
        μ1p = rand(Normal(0, 2.0))
        μ2p = rand(Normal(0, 2.0))
        ρp = rand(Uniform(-1, 1))
        μp = [μ1p, μ2p]
        Σp = [1.0 ρp; ρp 1.0]
        
        for n in 1:N
            zp = rand(MvNormal(μp, Σp))
            x_prior[s, n] = rand(BernoulliLogit(zp[1]))
            y_prior[s, n] = rand(BernoulliLogit(zp[2]))
        end
    end

    return (loglik=loglik, x_rep=x_rep, y_rep=y_rep, x_prior=x_prior, y_prior=y_prior)
end

# Run generated quantities for the correlation model
gq_vanilla_correlation = generated_quantities_correlation(chain_vanilla_correlation, d.x, d.y)

# Plot predictive checks for y
predictive_checks_regression(gq_vanilla_correlation.y_rep, gq_vanilla_correlation.y_prior; d=d)

```

Computing the marginal log-likelihood and LOOIC for the correlation model:

```{julia}
# Compute log-likelihood
logdensity_func_vanilla_correlation = create_logdensity_function(model_vanilla_correlation)


samples_vanilla_correlation = [Vector(chain_vanilla_correlation[:ρ][:]) Vector(chain_vanilla_correlation[:μ1][:]) Vector(chain_vanilla_correlation[:μ2][:])]

logml_vanilla_correlation = bridge_sampling(samples_vanilla_correlation, logdensity_func_vanilla_correlation)

println("Marginal log-likelihood: ", logml_vanilla_correlation)

```